kind: PersistentVolume
apiVersion: v1
metadata:
  name: meu-vol
  labels:
    type: local
spec:
  capacity:
    storage: 150M
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /k8s
    server: 192.168.10.40
    readOnly: false
